package cc.kave.commons.utils.json;

import cc.kave.commons.model.names.AliasName;
import cc.kave.commons.model.names.BundleName;
import cc.kave.commons.model.names.DelegateTypeName;
import cc.kave.commons.model.names.EventName;
import cc.kave.commons.model.names.FieldName;
import cc.kave.commons.model.names.LambdaName;
import cc.kave.commons.model.names.LocalVariableName;
import cc.kave.commons.model.names.MethodName;
import cc.kave.commons.model.names.Name;
import cc.kave.commons.model.names.NamespaceName;
import cc.kave.commons.model.names.ParameterName;
import cc.kave.commons.model.names.PropertyName;
import cc.kave.commons.model.names.TypeName;
import cc.kave.commons.model.names.csharp.CsAliasName;
import cc.kave.commons.model.names.csharp.CsAssemblyName;
import cc.kave.commons.model.names.csharp.CsDelegateTypeName;
import cc.kave.commons.model.names.csharp.CsEventName;
import cc.kave.commons.model.names.csharp.CsFieldName;
import cc.kave.commons.model.names.csharp.CsLambdaName;
import cc.kave.commons.model.names.csharp.CsLocalVariableName;
import cc.kave.commons.model.names.csharp.CsMethodName;
import cc.kave.commons.model.names.csharp.CsName;
import cc.kave.commons.model.names.csharp.CsNamespaceName;
import cc.kave.commons.model.names.csharp.CsParameterName;
import cc.kave.commons.model.names.csharp.CsPropertyName;
import cc.kave.commons.model.names.csharp.CsTypeName;
import cc.kave.commons.model.ssts.IExpression;
import cc.kave.commons.model.ssts.IMemberDeclaration;
import cc.kave.commons.model.ssts.IReference;
import cc.kave.commons.model.ssts.ISST;
import cc.kave.commons.model.ssts.IStatement;
import cc.kave.commons.model.ssts.blocks.ICaseBlock;
import cc.kave.commons.model.ssts.blocks.ICatchBlock;
import cc.kave.commons.model.ssts.blocks.IDoLoop;
import cc.kave.commons.model.ssts.blocks.IForEachLoop;
import cc.kave.commons.model.ssts.blocks.IForLoop;
import cc.kave.commons.model.ssts.blocks.IIfElseBlock;
import cc.kave.commons.model.ssts.blocks.ILockBlock;
import cc.kave.commons.model.ssts.blocks.ISwitchBlock;
import cc.kave.commons.model.ssts.blocks.ITryBlock;
import cc.kave.commons.model.ssts.blocks.IUncheckedBlock;
import cc.kave.commons.model.ssts.blocks.IUnsafeBlock;
import cc.kave.commons.model.ssts.blocks.IUsingBlock;
import cc.kave.commons.model.ssts.blocks.IWhileLoop;
import cc.kave.commons.model.ssts.declarations.IDelegateDeclaration;
import cc.kave.commons.model.ssts.declarations.IEventDeclaration;
import cc.kave.commons.model.ssts.declarations.IFieldDeclaration;
import cc.kave.commons.model.ssts.declarations.IMethodDeclaration;
import cc.kave.commons.model.ssts.declarations.IPropertyDeclaration;
import cc.kave.commons.model.ssts.declarations.IVariableDeclaration;
import cc.kave.commons.model.ssts.expressions.IAssignableExpression;
import cc.kave.commons.model.ssts.expressions.ILoopHeaderExpression;
import cc.kave.commons.model.ssts.expressions.ISimpleExpression;
import cc.kave.commons.model.ssts.expressions.assignable.ICompletionExpression;
import cc.kave.commons.model.ssts.expressions.assignable.IComposedExpression;
import cc.kave.commons.model.ssts.expressions.assignable.IIfElseExpression;
import cc.kave.commons.model.ssts.expressions.assignable.IInvocationExpression;
import cc.kave.commons.model.ssts.expressions.assignable.ILambdaExpression;
import cc.kave.commons.model.ssts.expressions.loopheader.ILoopHeaderBlockExpression;
import cc.kave.commons.model.ssts.expressions.simple.IConstantValueExpression;
import cc.kave.commons.model.ssts.expressions.simple.INullExpression;
import cc.kave.commons.model.ssts.expressions.simple.IReferenceExpression;
import cc.kave.commons.model.ssts.expressions.simple.IUnknownExpression;
import cc.kave.commons.model.ssts.impl.SST;
import cc.kave.commons.model.ssts.impl.blocks.CaseBlock;
import cc.kave.commons.model.ssts.impl.blocks.CatchBlock;
import cc.kave.commons.model.ssts.impl.blocks.DoLoop;
import cc.kave.commons.model.ssts.impl.blocks.ForEachLoop;
import cc.kave.commons.model.ssts.impl.blocks.ForLoop;
import cc.kave.commons.model.ssts.impl.blocks.IfElseBlock;
import cc.kave.commons.model.ssts.impl.blocks.LockBlock;
import cc.kave.commons.model.ssts.impl.blocks.SwitchBlock;
import cc.kave.commons.model.ssts.impl.blocks.TryBlock;
import cc.kave.commons.model.ssts.impl.blocks.UncheckedBlock;
import cc.kave.commons.model.ssts.impl.blocks.UnsafeBlock;
import cc.kave.commons.model.ssts.impl.blocks.UsingBlock;
import cc.kave.commons.model.ssts.impl.blocks.WhileLoop;
import cc.kave.commons.model.ssts.impl.declarations.DelegateDeclaration;
import cc.kave.commons.model.ssts.impl.declarations.EventDeclaration;
import cc.kave.commons.model.ssts.impl.declarations.FieldDeclaration;
import cc.kave.commons.model.ssts.impl.declarations.MethodDeclaration;
import cc.kave.commons.model.ssts.impl.declarations.PropertyDeclaration;
import cc.kave.commons.model.ssts.impl.expressions.assignable.CompletionExpression;
import cc.kave.commons.model.ssts.impl.expressions.assignable.ComposedExpression;
import cc.kave.commons.model.ssts.impl.expressions.assignable.IfElseExpression;
import cc.kave.commons.model.ssts.impl.expressions.assignable.InvocationExpression;
import cc.kave.commons.model.ssts.impl.expressions.assignable.LambdaExpression;
import cc.kave.commons.model.ssts.impl.expressions.loopheader.LoopHeaderBlockExpression;
import cc.kave.commons.model.ssts.impl.expressions.simple.ConstantValueExpression;
import cc.kave.commons.model.ssts.impl.expressions.simple.NullExpression;
import cc.kave.commons.model.ssts.impl.expressions.simple.ReferenceExpression;
import cc.kave.commons.model.ssts.impl.expressions.simple.UnknownExpression;
import cc.kave.commons.model.ssts.impl.references.EventReference;
import cc.kave.commons.model.ssts.impl.references.FieldReference;
import cc.kave.commons.model.ssts.impl.references.MethodReference;
import cc.kave.commons.model.ssts.impl.references.PropertyReference;
import cc.kave.commons.model.ssts.impl.references.UnknownReference;
import cc.kave.commons.model.ssts.impl.references.VariableReference;
import cc.kave.commons.model.ssts.impl.statements.Assignment;
import cc.kave.commons.model.ssts.impl.statements.BreakStatement;
import cc.kave.commons.model.ssts.impl.statements.ContinueStatement;
import cc.kave.commons.model.ssts.impl.statements.ExpressionStatement;
import cc.kave.commons.model.ssts.impl.statements.GotoStatement;
import cc.kave.commons.model.ssts.impl.statements.LabelledStatement;
import cc.kave.commons.model.ssts.impl.statements.ReturnStatement;
import cc.kave.commons.model.ssts.impl.statements.ThrowStatement;
import cc.kave.commons.model.ssts.impl.statements.UnknownStatement;
import cc.kave.commons.model.ssts.impl.statements.VariableDeclaration;
import cc.kave.commons.model.ssts.references.IAssignableReference;
import cc.kave.commons.model.ssts.references.IEventReference;
import cc.kave.commons.model.ssts.references.IFieldReference;
import cc.kave.commons.model.ssts.references.IMemberReference;
import cc.kave.commons.model.ssts.references.IMethodReference;
import cc.kave.commons.model.ssts.references.IPropertyReference;
import cc.kave.commons.model.ssts.references.IUnknownReference;
import cc.kave.commons.model.ssts.references.IVariableReference;
import cc.kave.commons.model.ssts.statements.IAssignment;
import cc.kave.commons.model.ssts.statements.IBreakStatement;
import cc.kave.commons.model.ssts.statements.IContinueStatement;
import cc.kave.commons.model.ssts.statements.IExpressionStatement;
import cc.kave.commons.model.ssts.statements.IGotoStatement;
import cc.kave.commons.model.ssts.statements.ILabelledStatement;
import cc.kave.commons.model.ssts.statements.IReturnStatement;
import cc.kave.commons.model.ssts.statements.IThrowStatement;
import cc.kave.commons.model.ssts.statements.IUnknownStatement;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public abstract class JsonUtils {
	public static <T> T parseJson(String json, Class<T> targetType) {
		Gson gson = createGson();
		return gson.fromJson(json, targetType);
	}

	public static String toString(Object instance) {
		Gson gson = createGson();
		return gson.toJson(instance);
	}

	private static Gson createGson() {
		GsonBuilder gsonBuilder = new GsonBuilder();
		// name interface types
		gsonBuilder.registerTypeAdapter(AliasName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(BundleName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(EventName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(FieldName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(LambdaName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(LocalVariableName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(MethodName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(Name.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(NamespaceName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(ParameterName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(PropertyName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(TypeName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(DelegateTypeName.class, new GsonNameAdapter());
		// C# name types
		gsonBuilder.registerTypeAdapter(CsAliasName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsAssemblyName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsEventName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsFieldName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsLambdaName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsLocalVariableName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsMethodName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsNamespaceName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsParameterName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsPropertyName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsTypeName.class, new GsonNameAdapter());
		gsonBuilder.registerTypeAdapter(CsDelegateTypeName.class, new GsonNameAdapter());

		// IMemberDeclaration interfaces
		gsonBuilder.registerTypeAdapter(IMemberDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IDelegateDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IEventDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IFieldDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IMethodDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IPropertyDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IAssignableReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IMemberReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IEventReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IFieldReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IPropertyReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IUnknownReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IVariableReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(IMethodReference.class, new GsonIMemberDeclarationDeserializer());
		// IMemberDeclaration implementation
		gsonBuilder.registerTypeAdapter(DelegateDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(EventDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(FieldDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(MethodDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(PropertyDeclaration.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(EventReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(FieldReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(PropertyReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(UnknownReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(VariableReference.class, new GsonIMemberDeclarationDeserializer());
		gsonBuilder.registerTypeAdapter(MethodReference.class, new GsonIMemberDeclarationDeserializer());

		// IExpression interfaces
		gsonBuilder.registerTypeAdapter(IExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IAssignableExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ILoopHeaderExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ICompletionExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IComposedExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IIfElseExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IInvocationExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ILambdaExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ISimpleExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ILoopHeaderBlockExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IConstantValueExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(INullExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IReferenceExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IUnknownExpression.class, new GsonIExpressionDeserializer());
		// IExpression implementations
		gsonBuilder.registerTypeAdapter(CompletionExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ComposedExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(IfElseExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(InvocationExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(LambdaExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ConstantValueExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(NullExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(ReferenceExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(UnknownExpression.class, new GsonIExpressionDeserializer());
		gsonBuilder.registerTypeAdapter(LoopHeaderBlockExpression.class, new GsonIExpressionDeserializer());

		// IStatement interfaces
		gsonBuilder.registerTypeAdapter(IStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IAssignment.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IBreakStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IContinueStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IDoLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IExpressionStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IForEachLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IForLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IGotoStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IIfElseBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ILabelledStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ILockBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IReturnStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ISwitchBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IThrowStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ITryBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IUncheckedBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IUnknownStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IUnsafeBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IUsingBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IVariableDeclaration.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IWhileLoop.class, new GsonIStatementDeserializer());
		// IStatement implementation
		gsonBuilder.registerTypeAdapter(Assignment.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(BreakStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ContinueStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(DoLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ExpressionStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ForEachLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ForLoop.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(GotoStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(IfElseBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(LabelledStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(LockBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ReturnStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(SwitchBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(ThrowStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(TryBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(UncheckedBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(UnknownStatement.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(UnsafeBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(UsingBlock.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(VariableDeclaration.class, new GsonIStatementDeserializer());
		gsonBuilder.registerTypeAdapter(WhileLoop.class, new GsonIStatementDeserializer());
		// Case and CatchBlock
		gsonBuilder.registerTypeAdapter(ICatchBlock.class, new GsonCatchBlockDeserializer());
		gsonBuilder.registerTypeAdapter(CatchBlock.class, new GsonCatchBlockDeserializer());
		gsonBuilder.registerTypeAdapter(ICaseBlock.class, new GsonCaseBlockDeserializer());
		gsonBuilder.registerTypeAdapter(CaseBlock.class, new GsonCaseBlockDeserializer());

		// SST
		gsonBuilder.registerTypeAdapter(ISST.class, new GsonISSTDeserializer());
		gsonBuilder.registerTypeAdapter(SST.class, new GsonISSTDeserializer());
		Gson gson = gsonBuilder.create();
		return gson;
	}
}
